version: "3.9"

services:
  db:
    image: postgres:18
    container_name: postgres_gift
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/pgdata
    networks:
      - tg_gift_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB} -d ${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  tg_gift_notification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_gift_notification
    environment:
      HOST: postgres_gift
      DATABASE_PORT: 5432
      USER: ${USER_DB}
      PASSWORD: ${PASSWORD}
      DATABASE: ${DATABASE}
      TG_API: ${TG_API}

    volumes:
      - ./logs:/logs
    depends_on:
      - db
    networks:
      - tg_gift_network

volumes:

  pgdata:
    driver: local

  logs:
    driver: local


networks:
  tg_gift_network:
    driver: bridge
