version: "3.9"

services:

  tg_gift_notification:
    build:
      context: .
      dockerfile: Dockerfile
      
    environment:
      - ip=postgres_sale_of_cours
      - DATABASE_PORT=5433     
      - user=${user}
      - password=${password}
      - DATABASE=${DATABASE}
      - TG_API=${TG_API}
    networks:
      - sale_of_cours_bot_postgres_network

networks:
  sale_of_cours_bot_postgres_network:
    external: true

