version: "3.9"
###docker network create --driver bridge sale_of_cours_bot_postgres_network
services:
  tg_gift_notification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_gift_notification
    environment:
      - ip=postgres_sale_of_cours
      - DATABASE_PORT=5432
      - user=${user}
      - password=${password}
      - DATABASE=${DATABASE}
      - TG_API=${TG_API}
    networks:
      - sale_of_cours_bot_postgres_network

networks:
  sale_of_cours_bot_postgres_network:
    external: true
